ThumbWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thumb.Lib.USBs;

namespace ThumbWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

         
            return View();
        }
      

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ThumbWeb/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThumbWeb.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }
    }
}

ThumbWeb/Controllers/USBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thumb.Lib.USBs;

namespace ThumbWeb.Controllers
{
    public class USBController : Controller
    {

        public ActionResult Add()
        {


            return View();
        }
        // GET: USB
        [HttpPost]
        public ActionResult Add(string IssuedTo, string IssuedBy, string Quantity, string TypeOfLog)
        {

            USBManager.Add(TypeOfLog, DateTime.Now, IssuedBy, IssuedTo, Convert.ToInt32(Quantity));


            //Controller method



            ViewBag.Message = "Saved!";

            return Add();
        }

        public ActionResult Edit(long id)
        {
          var item =   USBManager.Get(id);

            return View(item);
        }
        // GET: USB
        [HttpPost]
        public ActionResult Edit(long id, string IssuedTo, string IssuedBy, string Quantity, string TypeOfLog)
        {

            USBManager.Edit(id, TypeOfLog, DateTime.Now, IssuedBy, IssuedTo, Convert.ToInt32(Quantity));


            //Controller method



            ViewBag.Message = "Saved!";

            return Redirect("ViewUsbs");
        }

        //for EACH method  there MUST be a corresponding view to it.
        public ActionResult ViewUsbs()
        {

            var usbItems = USBManager.GetAll();


            return View(usbItems);
        }
    }
}

ThumbWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ThumbWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


@*Bootstrap for UI designs*@


@*jquery to access the C# code in an actionresult WITHOUT doing a full form post*@

ThumbWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("USB and Label Log", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("USBs", "ViewUsbs", "USB")</li>
                    <li>@Html.ActionLink("RFIDs", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ThumbWeb/Views/USB/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@*Bootstrap for UI designs*@


@*jquery to access the C# code in an actionresult WITHOUT doing a full form post*@




<a href="/USB/ViewUsbs">View USBs</a>

<br /><br /><br />
<form action="/USB/Add" method="post">

    <div>
        <div>
            <span>
                Type of Log
            </span>
            <select id="TypeOfLog" name="TypeOfLog">
                <option value="USBs" title="USBs" label="USBs"></option>

                <option value="LABELs" title="LABELs" label="LABELs"></option>
            </select>

        </div>



        <div>
            <span>
                Issued To

            </span>
            <input type="text" id="IssuedTo" name="IssuedTo" />


        </div>


        <div>
            <span>
                Issued By

            </span>
            <input type="text" id="IssuedBy" name="IssuedBy" />


        </div>

        <div>
            <span>
                Quantity

            </span>
            <input type="text" id="Quantity" name="Quantity" />


        </div>

        <div>
            <span>
                Issued To

            </span>
            <input type="text" id="IssuedTo" class="form-control" name="IssuedTo" />


        </div>

        @ViewBag.Message


        @*type submitt buttons post data back to controller level.*@
        <button id="BTN" type="submit" class="btn btn-default" value="save">SAVE</button>
    </div>
</form>

ThumbWeb/Views/USB/Edit.cshtml
@model Thumb.Lib.USBs.USBItem
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@*Bootstrap for UI designs*@


@*jquery to access the C# code in an actionresult WITHOUT doing a full form post*@




<a href="/USB/ViewUsbs">View USBs</a>

<br /><br /><br />
<form action="/USB/Edit" method="post">

    <div>
        <div>
            <span>
                Type of Log
            </span>
            <select id="TypeOfLog" name="TypeOfLog">
                <option value="USBs" title="USBs" label="USBs"></option>

                <option value="LABELs" title="LABELs" label="LABELs"></option>
            </select>

        </div>



        <div>
            <span>
                Issued To

            </span>
            <input type="text" id="IssuedTo" value="@Model.Entity_issued_to" name="IssuedTo" />


        </div>


        <div>
            <span>
                Issued By

            </span>
            <input type="text" id="IssuedBy" value="@Model.Issued_by" name="IssuedBy" />


        </div>

        <div>
            <span>
                Quantity

            </span>
            <input type="text" id="Quantity" view="@Model.Quantity_issued" name="Quantity" />


        </div>

        <div>
            <span>
                Issued To

            </span>
            <input type="text" id="IssuedTo" class="form-control" name="IssuedTo" />


        </div>

        @ViewBag.Message


        @*type submitt buttons post data back to controller level.*@
        <button id="BTN" type="submit" class="btn btn-default" value="save">SAVE</button>
    </div>
    @Html.HiddenFor(x=>x.Id)
</form>

ThumbWeb/Views/USB/ViewUsbs.cshtml
@model List<Thumb.Lib.USBs.USBItem>

@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<a class="btn btn-default" href="/USB/Add">Add USBs</a>

<br /><br /><br />


<table class="table table-striped table-bordered table-hover">

    <tr>
        <th></th>
        <th>Issued To</th>
        <th>Issued By</th>
        <th>Quantity Issued</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><a class="btn btn-default" href="/USB/Edit?id=@item.Id">Edit</a></td>
            <td>@item.Entity_issued_to</td>
            <td>@item.Issued_by</td>
            <td>@item.Quantity_issued</td>
            <td>@item.Entity_issued_to</td>


        </tr>


    }

        <tr>
            <th></th>
            <th>Issued To</th>
            <th>Issued By</th>
            <th>Quantity Issued</th>
            <th></th>
        </tr>
</table>